---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install dirmngr in order to be able to install the apt signing key
  apt:
    pkg:
      - dirmngr
      - apt-transport-https
- name: Add Microsoft apt signing key on remote server to keyring
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    keyserver: keyserver.ubuntu.com
    keyring: /etc/apt/trusted.gpg.d/microsoftpackages.gpg
- name: Add apt repo for vs code
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/microsoftpackages.gpg] https://packages.microsoft.com/repos/vscode stable main
    # setting filename required to not collide with
    # https://github.com/microsoft/vscode/blob/master/resources/linux/debian/postinst.template
    filename: vscode
    state: present
- name: Install visual studio code package
  apt:
    pkg:
      - code
- name: Check whether sync-settings extension installed
  find:
    paths: "~/.vscode/extensions"
    patterns: "zokugun.sync-settings*"
    file_type: directory
    recurse: no
  register: sync_settings_ext_find
  become: no
- name: Install additional packages in order to be able to run the extension installation below
# Might be obsolete with the official settings sync function
  apt:
    pkg:
      - libx11-xcb1
      - libasound2
      - libxshmfence1
- name: Install code-settings-sync extension
  command: code --install-extension zokugun.sync-settings
  become: no
  when: not sync_settings_ext_find.matched
  changed_when: false
